import fs from 'fs';
import path from 'path';

const REPO_NAME = 'Adventure Forge - Backend API';
const IGNORE_DIRS = ['node_modules', '.git', 'dist', '.vscode'];

function generateMap(dir, depth = 0) {
    let map = '';
    const files = fs.readdirSync(dir);
    
    files.forEach(file => {
        if (IGNORE_DIRS.includes(file)) return;
        
        const fullPath = path.join(dir, file);
        const stats = fs.statSync(fullPath);
        const indent = '  '.repeat(depth);
        
        if (stats.isDirectory()) {
            map += `${indent}- **${file}/**\n`;
            map += generateMap(fullPath, depth + 1);
        } else if (file.endsWith('.ts')) {
            map += `${indent}- ${file}\n`;
        }
    });
    return map;
}

const codeMap = `
# CODE_MAP.md - ${REPO_NAME}
*Auto-generated by agent-toolbox*

## Architecture Overview
- **src/ai**: Core service for LLM orchestration (Gemini, Puter, Pollinations).
- **src/game**: Game logic and streaming controllers.
- **src/schemas**: Mongoose models for GameState and Stories.
- **src/auth**: Google OAuth implementation.

## File Structure
${generateMap('./src')}
`;

fs.writeFileSync('CODE_MAP.md', codeMap);
console.log('✅ CODE_MAP.md generated for Backend');
